### ISSUE TITLE
Downloads from bitcoin.org are really slow

### ISSUE THREAD

**Issue by patrikr** [bitcoin/bitcoin.org#712]
I downloaded https://bitcoin.org/bin/0.10.0/test/bitcoin-0.10.0rc3-win32.zip, and it was really slow. The download took 24 minutes, which means about 21 kB/s.

This was the case already a while ago when I downloaded RC1, and when I mentioned it on IRC, some people said bitcoin.org was not slow for them. So this looks like you are slowing the download down on purpose for some people. (Or your upstream provider is.)

I'm in Finland, but it's not  a problem with the transatlantic connection, every other web site is fast, as normal.

Could you please fix this? Or even better, provide BitTorrents. That would reduce your bandwidth usage and speed up downloads by a lot for everyone. You don't even need to run a tracker or have torrent files nowadays, just publish magnet URLs.

**Comment by harding** [comment]
I also had a slow download today (around 15:00 UTC) of RC3 from New Jersey, USA.  It was about twice as fast as the speed you reported, which is still fairly slow for my connection.  Oddly, I haven't noticed any problem with the pages on this site loading slowly---although I guess I have them mostly cached.

I do believe a magnet link will be provided for the final release---it's in the 0.10.0 pull request, https://github.com/bitcoin/bitcoin.org/pull/664

**Comment by saivann** [comment]
Thanks for reporting the issue! The problem seems to be also affecting the canadian visitor that I am... I have forwarded the issue to Black Lotus. The server bandwidth is far from being overloaded at the moment and download speeds were good in the past, so this likely is something on their side.

Torrent downloads will indeed be provided in the future!

**Comment by gurnec** [comment]
For what it's worth, I'm seeing similar problems from my location as well (East Coast US). It's intermittent, though. Somewhere around 25-ish % of each download attempt is affected, while the other attempts are nice and fast.

For a given set of layer 4 parameters (src & dst IPs and ports), the issue is either consistently present or not present, even across multiple connections. In other words, if I take note of the src port of a slow connection, and then retry a download using the same src port (making sure my NAT box doesn't muck with it), it remains slow.

This is a common symptom of network load balancing where one of a few alternative communications lines (or NICs) is having issues. Each packet's layer 4 data is typically hashed in order to choose a communications line (or server) to process a particular layer 4 stream (with the same line handling every packet whose layer 4 header matches). It's not very common amongst application-layer load balancers (e.g. nginx), which tend to track individual connections regardless of port re-use.

I guess we'll wait and see....

**Comment by saivann** [comment]
If someone here is still able to reproduce the issue, can you email me (saivann@gmail.com) with the result of the following command lines?

wget https://www.blacklotus.net/speedtests/10mb.bin
wget https://bitcoin.org/bin/0.9.3/bitcoin-0.9.3-win32-setup.exe
traceroute bitcoin.org

(@patrikr if you can tell what is the current download speed for both links seen above, this can be helpful)

All in all, none of Black Lotus employees are able to reproduce the issue on their side, and it seems like my own connection is too unstable right now for me to rely on it.

**Comment by saivann** [comment]
Note; Just edited one of the command lines above

**Comment by harding** [comment]
@saivann I get 800 to 900 KBytes/s for all three links from my home connection (which is about my top non-burst speed) and 14 MBytes/s for the 0.9.3 link from one of my VPSes also located in New Jersey, USA (that's effectively my top speed for that VPS).

So, for me, the problem is resolved.  I'll check again a few times tomorrow and post if I see any other slowdowns.

Thanks for investigating!

**Comment by patrikr** [comment]
@saivann 

    C:\Documents and Settings\Patrik>wget
    'wget' is not recognized as an internal or external command,
    operable program or batch file.

;) I can give you the approximate speeds shown by Chrome:

* 10mb.bin: 300+ kB/s
* 10MB.zip: 1200+ kB/s
* bitcoin-0.9.3-win32-setup.exe: 300+ kB/s

I also tried RC3 again, it is also downloading at 300+ kB/s now. My network connection is 100 megabits BTW.

**Comment by gurnec** [comment]
FYI I'm still seeing the same intermittent issues as I was yesterday (from multiple locations), although they seem less severe today. @saivann I'll send you an email with some test results.

**Comment by saivann** [comment]
A (late) follow-up: Black Lotus concluded the issue wasn't on their side and given that the issue seems to have mostly mitigated, I am closing the issue for now. However if someone notices any degradation or thinks of possible ideas for improvements, please comment or re-open an issue. Thank you all for your help and testing!
